# Generated by Django 4.2.6 on 2023-10-16 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_owner_alter_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 17, 6, 4, 45373, tzinfo=datetime.timezone.utc), verbose_name='последняя отправка уведомления'),
        ),
    ]
