# Generated by Django 4.2.6 on 2023-10-16 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_habit_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='последняя отправка уведомления'),
        ),
    ]
