# Generated by Django 4.2.6 on 2023-10-17 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_alter_habit_last_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['id'], 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 22, 54, 19, 495443), verbose_name='последняя отправка уведомления'),
        ),
    ]
