# Generated by Django 4.2.6 on 2023-11-04 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_alter_habit_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 13, 20, 46, 804966), verbose_name='последняя отправка уведомления'),
        ),
    ]
