# Generated by Django 4.2.6 on 2023-11-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0008_alter_habit_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_time',
            field=models.DateTimeField(verbose_name='последняя отправка уведомления'),
        ),
    ]
